"""
Quant X Capital — Streamlit Trading Dashboard
Run with: streamlit run gui/dashboard.py (from the project root)

[Data Priority]
  The Live Monitor / TCA pages prefer local SQLite data (from Paper Trading).
  If the database is empty (e.g. Streamlit Cloud deployment), they automatically
  fall back to backtest_cache.json so the dashboard always has real data to display.
"""

import sys
import os
import json
from datetime import datetime

sys.path.append(os.path.join(os.path.dirname(__file__), ".."))

try:
    import streamlit as st
    import pandas as pd
except ImportError:
    print("Please install dependencies: pip install streamlit pandas")
    sys.exit(1)

from database.db_manager import (
    get_account_history, get_current_positions,
    get_recent_orders, init_database
)

# ================================================================
# Page configuration
# ================================================================

st.set_page_config(
    page_title="Quant X Capital — Trading Dashboard",
    page_icon="📈",
    layout="wide",
    initial_sidebar_state="expanded",
)

# ================================================================
# Sidebar
# ================================================================

st.sidebar.title("⚙️ Quant X Capital")
st.sidebar.markdown("**Multi-Factor Momentum | BTC/USDT**")
st.sidebar.divider()

mode = st.sidebar.radio(
    "View Mode",
    ["Live Monitor", "Backtest Analysis", "TCA Cost Analysis"],
    index=0,
)

st.sidebar.divider()
st.sidebar.markdown("Starting Capital: **50,000 USDT**")
st.sidebar.markdown("Instrument: **BTC/USDT**")
st.sidebar.markdown("Strategy: **Multi-Factor Momentum**")
st.sidebar.divider()
if st.sidebar.button("🔄 Refresh"):
    st.cache_data.clear()
    st.rerun()

# ================================================================
# Backtest cache loading (read-only file, millisecond-level, no live computation)
#
# Note: backtest_cache.json is auto-generated by `python main.py --backtest`.
#       Do not edit manually — the GUI reads it directly to ensure full consistency.
# ================================================================

CACHE_FILE = os.path.abspath(
    os.path.join(os.path.dirname(__file__), "..", "backtest_cache.json")
)

@st.cache_data(ttl=3600)
def load_backtest_cache():
    """Load pre-computed results from backtest_cache.json without re-running the backtest."""
    if not os.path.exists(CACHE_FILE):
        return None, [], [], []
    try:
        with open(CACHE_FILE, "r") as f:
            metrics = json.load(f)
        equity    = metrics.get("equity_curve", [])
        benchmark = metrics.get("benchmark_curve", [])
        trades    = metrics.get("trades", [])
        return metrics, equity, benchmark, trades
    except Exception:
        return None, [], [], []


def downsample(data: list, n: int = 400) -> list:
    """Uniformly downsample a list to at most n points to avoid chart lag."""
    if len(data) <= n:
        return data
    step = len(data) / n
    return [data[int(i * step)] for i in range(n)]


def trades_to_display_df(trades: list) -> pd.DataFrame:
    """Convert a backtest trade list to a display-ready DataFrame."""
    rows = []
    for t in trades:
        rows.append({
            "Direction":      "buy" if t.get("action") == "buy" else "sell",
            "Price (USDT)":   f"{t.get('price', 0):,.2f}",
            "Qty (BTC)":      f"{t.get('qty', 0):.6f}",
            "Fee (USDT)":     f"{t.get('fee', 0):.4f}",
            "P&L (USDT)":     f"{t.get('pnl', 0):+.2f}" if t.get("action") == "sell" else "—",
            "Factor Score":   f"{t.get('score', 0):.4f}" if t.get("score") is not None else "—",
        })
    return pd.DataFrame(rows)


# ================================================================
# Live Monitor page
# ================================================================

if mode == "Live Monitor":
    st.title("📈 Quant X Capital — Live Monitor")
    init_database()

    # Load backtest cache (fallback data source)
    bt_metrics, equity_curve, benchmark_curve, bt_trades = load_backtest_cache()

    # --- Account metric cards ---
    account_history = get_account_history()
    using_backtest_fallback = False

    if account_history and len(account_history) > 1:
        # Prefer Paper Trading live data
        latest       = account_history[-1]
        first        = account_history[0]
        total_value  = latest["total_value"]
        initial      = first["total_value"]
        total_pnl    = total_value - initial
        total_return = (total_pnl / initial * 100) if initial > 0 else 0
        cash         = latest["cash"]
        position_value = max(total_value - cash, 0)
    elif bt_metrics:
        # Fall back to backtest results
        using_backtest_fallback = True
        total_value    = bt_metrics.get("final_value", 50000)
        total_pnl      = total_value - 50000
        total_return   = bt_metrics.get("total_return", 0)
        cash           = bt_metrics.get("final_cash", total_value)
        position_value = max(total_value - cash, 0)
    else:
        total_value    = 50000.0
        total_pnl      = 0.0
        total_return   = 0.0
        cash           = 50000.0
        position_value = 0.0

    if using_backtest_fallback:
        st.info(
            "ℹ️ **Displaying backtest results** (period: 2026-04-12 to 2026-04-19). "
            "Once Paper Trading is started locally with `python main.py --live`, "
            "this page will automatically switch to live data.",
            icon="📊"
        )

    col1, col2, col3, col4 = st.columns(4)
    with col1:
        st.metric("💰 Account Value",
                  f"{total_value:,.2f} USDT",
                  f"{total_pnl:+.2f} USDT")
    with col2:
        st.metric("📊 Total Return",
                  f"{total_return:.2f}%",
                  "vs initial 50,000 USDT")
    with col3:
        st.metric("💵 Available Cash", f"{cash:,.2f} USDT")
    with col4:
        st.metric("🪙 Position Value", f"{position_value:,.2f} USDT")

    st.divider()

    # --- PnL curve + positions ---
    col_left, col_right = st.columns([2, 1])

    with col_left:
        st.subheader("📉 Account Value Curve (PnL Curve)")
        if account_history and len(account_history) > 1:
            df_equity = pd.DataFrame(account_history)
            df_equity["snapshot_at"] = pd.to_datetime(df_equity["snapshot_at"])
            df_equity = df_equity.set_index("snapshot_at")
            st.line_chart(df_equity["total_value"], color="#00ff88")
        elif equity_curve:
            sampled = downsample(equity_curve, 400)
            df_eq = pd.DataFrame({"Strategy Equity (USDT)": sampled})
            if benchmark_curve and len(benchmark_curve) > 1:
                sampled_bh = downsample(benchmark_curve, 400)
                min_len = min(len(sampled), len(sampled_bh))
                df_eq = pd.DataFrame({
                    "Strategy Equity (USDT)":    sampled[:min_len],
                    "Benchmark B&H (USDT)":      sampled_bh[:min_len],
                })
                st.line_chart(df_eq, color=["#00ff88", "#aaaaff"])
                st.caption("Green = Strategy | Blue = Buy-and-Hold Benchmark")
            else:
                st.line_chart(df_eq, color="#00ff88")
        else:
            st.info("Account value curve will appear once trading begins.")

    with col_right:
        st.subheader("🪙 Current Positions")
        positions = get_current_positions()
        if positions and not using_backtest_fallback:
            for pos in positions:
                st.markdown(f"**{pos['symbol']}**")
                ca, cb = st.columns(2)
                ca.metric("Quantity", f"{pos['qty']:.6f}")
                cb.metric("Unrealised P&L",
                          f"{pos['unrealized_pnl']:+.2f} USDT",
                          delta_color="normal")
                st.caption(f"Average Cost: {pos['avg_cost']:.2f} USDT")
        elif using_backtest_fallback and bt_metrics:
            final_holdings = bt_metrics.get("final_holdings", 0)
            final_price    = bt_metrics.get("final_price", 0)
            if final_holdings > 0:
                st.markdown("**BTC/USDT**")
                ca, cb = st.columns(2)
                ca.metric("Quantity", f"{final_holdings:.6f} BTC")
                cb.metric("Position Value", f"{final_holdings * final_price:,.2f} USDT")
            else:
                st.info("Flat at end of backtest")
                st.markdown("All BTC was liquidated at the last sell signal.")
        else:
            st.info("No open positions.")
            st.markdown("**BTC/USDT**: 0 BTC  \nWaiting for buy signal...")

    st.divider()

    # --- Recent trade log ---
    st.subheader("📋 Trade Log")
    db_orders = get_recent_orders(limit=20)

    def color_side(val):
        if val in ("buy",):
            return "background-color: #003300; color: #00ff00"
        elif val in ("sell",):
            return "background-color: #330000; color: #ff4444"
        return ""

    if db_orders:
        # Show database records when Paper Trading data exists
        df_orders = pd.DataFrame(db_orders)
        column_map = {
            "order_id":   "Order ID",
            "symbol":     "Symbol",
            "side":       "Direction",
            "price":      "Price (USDT)",
            "qty":        "Qty (BTC)",
            "status":     "Status",
            "created_at": "Time",
        }
        display_cols = [c for c in column_map if c in df_orders.columns]
        df_display = df_orders[display_cols].rename(columns=column_map)
        if "Price (USDT)" in df_display.columns:
            df_display["Price (USDT)"] = df_display["Price (USDT)"].apply(lambda x: f"{x:,.2f}")
        if "Qty (BTC)" in df_display.columns:
            df_display["Qty (BTC)"] = df_display["Qty (BTC)"].apply(lambda x: f"{x:.6f}")
        st.dataframe(
            df_display.style.map(color_side, subset=["Direction"]),
            use_container_width=True,
            height=min(300, 38 + len(df_display) * 35),
        )
        st.caption(f"{len(db_orders)} Paper Trading fill(s) recorded")

    elif bt_trades:
        # Fallback: show backtest fill records
        st.caption("📊 Showing backtest trade details (will be replaced by live data once Paper Trading starts)")
        df_bt = trades_to_display_df(bt_trades)
        st.dataframe(
            df_bt.style.map(color_side, subset=["Direction"]),
            use_container_width=True,
            height=min(400, 38 + len(df_bt) * 35),
        )
        st.caption(f"{len(bt_trades)} backtest trade(s) (BTC/USDT, 2026-04-12 to 2026-04-19)")
    else:
        st.info("No trade records available.")


# ================================================================
# Backtest Analysis page
# ================================================================

elif mode == "Backtest Analysis":
    st.title("🔬 Backtest Performance Analysis")

    metrics, equity_curve, benchmark_curve, bt_trades = load_backtest_cache()

    if metrics is None:
        st.error("Backtest cache not found. Run: `python main.py --backtest`")
        st.stop()

    # ---- Core metrics (values already stored as percentages in metrics dict) ----
    total_return   = metrics.get("total_return", 0)
    bh_return      = metrics.get("benchmark_return", 0)
    sharpe         = metrics.get("sharpe_ratio", 0)
    max_dd         = metrics.get("max_drawdown", 0)
    win_rate       = metrics.get("win_rate", 0)
    profit_fac     = metrics.get("profit_factor", 0)
    total_trades   = metrics.get("total_trades", 0)
    final_val      = metrics.get("final_value", 50000)
    net_profit     = final_val - 50000
    total_commission = metrics.get("total_commission", 0)
    total_slippage   = metrics.get("total_slippage", 0)

    col1, col2, col3 = st.columns(3)
    with col1:
        st.metric("📈 Total Return",
                  f"{total_return:.2f}%",
                  f"Net P&L {net_profit:+.2f} USDT")
        st.metric("🏆 Sharpe Ratio",
                  f"{sharpe:.2f}",
                  "Excellent > 1.0" if sharpe > 1 else "Needs improvement")
    with col2:
        st.metric("📉 Max Drawdown",
                  f"{max_dd:.2f}%",
                  "Risk controlled" if abs(max_dd) < 10 else "Caution: high risk",
                  delta_color="inverse")
        st.metric("🎯 Win Rate",
                  f"{win_rate:.2f}%",
                  f"{total_trades} trades total")
    with col3:
        st.metric("💹 Profit Factor",
                  f"{profit_fac:.2f}",
                  "Wins > Losses" if profit_fac > 1 else "Losses > Wins",
                  delta_color="normal" if profit_fac > 1 else "inverse")
        st.metric("💰 Final Capital", f"{final_val:,.2f} USDT")

    st.divider()

    # ---- Equity curve (with real Buy-and-Hold benchmark) ----
    st.subheader("📉 Equity Curve")
    st.caption(
        "📌 **Benchmark (Buy-and-Hold)** = Buy BTC with 95% of capital at the first bar's open, "
        "hold until the end. Strategy line above this benchmark means outperforming passive holding."
    )

    if equity_curve:
        sampled_eq = downsample(equity_curve, 400)
        if benchmark_curve and len(benchmark_curve) > 1:
            sampled_bh = downsample(benchmark_curve, 400)
            min_len = min(len(sampled_eq), len(sampled_bh))
            df_eq = pd.DataFrame({
                "Strategy Equity (USDT)": sampled_eq[:min_len],
                "Benchmark B&H (USDT)":   sampled_bh[:min_len],
            })
            st.line_chart(df_eq, color=["#00ff88", "#aaaaff"])
            st.caption(
                f"Green = Strategy Equity | Blue = Buy-and-Hold Benchmark "
                f"(bought at initial price, held to end)"
                f" | Points: {len(sampled_eq)} (downsampled from {len(equity_curve)})"
            )
        else:
            df_eq = pd.DataFrame({"Strategy Equity (USDT)": sampled_eq})
            st.line_chart(df_eq, color=["#00ff88"])
            st.info("Old cache has no benchmark data. Re-run `python main.py --backtest` to update.")
    else:
        st.info("No equity curve data available.")

    st.divider()

    # ---- Detailed statistics ----
    st.subheader("📋 Detailed Backtest Statistics")
    col_a, col_b = st.columns(2)

    with col_a:
        st.markdown("**📊 Performance Summary**")
        perf_data = {
            "Metric": ["Starting Capital", "Final Capital", "Net P&L", "Total Return",
                       "Benchmark Return (B&H)", "Excess Return",
                       "Sharpe Ratio", "Profit Factor"],
            "Value": [
                "50,000.00 USDT",
                f"{final_val:,.2f} USDT",
                f"{net_profit:+.2f} USDT",
                f"{total_return:.2f}%",
                f"{bh_return:.2f}%",
                f"{total_return - bh_return:+.2f}%",
                f"{sharpe:.2f}",
                f"{profit_fac:.2f}",
            ],
        }
        st.dataframe(pd.DataFrame(perf_data), use_container_width=True, hide_index=True)

    with col_b:
        st.markdown("**⚠️ Risk & Costs**")
        risk_data = {
            "Metric": ["Max Drawdown", "Win Rate", "Total Trades",
                       "Total Commission", "Total Slippage",
                       "Backtest Period", "Data Frequency", "Commission Rate"],
            "Value": [
                f"{max_dd:.2f}%",
                f"{win_rate:.2f}%",
                f"{total_trades} trades",
                f"{total_commission:.2f} USDT",
                f"{total_slippage:.2f} USDT",
                "2026-04-12 to 2026-04-19 (7 days)",
                "1-minute candles",
                "0.10% (Binance spot)",
            ],
        }
        st.dataframe(pd.DataFrame(risk_data), use_container_width=True, hide_index=True)

    st.divider()

    # ---- Per-trade backtest log ----
    st.subheader("📋 Per-Trade Backtest Log")

    if bt_trades:
        rows = []
        cumulative_pnl = 0.0
        for t in bt_trades:
            action   = t.get("action", "—")
            price    = t.get("price", 0)
            qty      = t.get("qty", 0)
            fee      = t.get("fee", 0)
            slippage = t.get("slippage", 0)
            pnl      = t.get("pnl", None)
            score    = t.get("score", None)
            trade_val = price * qty

            # Convert millisecond timestamp to readable time
            ts = t.get("time", 0)
            try:
                trade_time = datetime.fromtimestamp(ts / 1000).strftime("%Y-%m-%d %H:%M")
            except Exception:
                trade_time = "—"

            if pnl is not None:
                cumulative_pnl += pnl

            rows.append({
                "Time":              trade_time,
                "Direction":         "🟢 Buy" if action == "buy" else "🔴 Sell",
                "Fill Price (USDT)": f"{price:,.2f}",
                "Qty (BTC)":         f"{qty:.6f}",
                "Trade Value (USDT)":f"{trade_val:,.2f}",
                "Fee (USDT)":        f"{fee:.2f}",
                "Slippage (USDT)":   f"{slippage:.2f}",
                "Trade P&L (USDT)":  f"{pnl:+.2f}" if pnl is not None else "—",
                "Cumul. P&L (USDT)": f"{cumulative_pnl:+.2f}" if pnl is not None else "—",
                "Factor Score":      f"{score:.4f}" if score is not None else "—",
            })

        df_trades = pd.DataFrame(rows)
        st.dataframe(df_trades, use_container_width=True, hide_index=True,
                     height=min(500, 38 + len(df_trades) * 38))

        sell_pnls  = [t.get("pnl", 0) for t in bt_trades
                      if t.get("action") == "sell" and t.get("pnl") is not None]
        total_fee  = sum(t.get("fee", 0) for t in bt_trades)
        total_slip = sum(t.get("slippage", 0) for t in bt_trades)
        n_buy  = sum(1 for t in bt_trades if t.get("action") == "buy")
        n_sell = sum(1 for t in bt_trades if t.get("action") == "sell")
        st.caption(
            f"**{len(bt_trades)}** trade(s) total ({n_buy} buy / {n_sell} sell) | "
            f"Cumulative P&L: **{sum(sell_pnls):+.2f} USDT** | "
            f"Total Fee: **{total_fee:.2f} USDT** | "
            f"Total Slippage: **{total_slip:.2f} USDT**"
        )
    else:
        st.info("No backtest trade records. Run `python main.py --backtest` to generate them.")

    st.divider()

    # ---- Strategy description ----
    st.subheader("📖 Strategy Description")
    st.markdown("""
    ### Multi-Factor Momentum Strategy

    **Core idea:** Combine three market signal dimensions into a composite score
    to determine buy/sell timing.

    | Factor | Weight | Meaning |
    |--------|--------|---------|
    | Price Momentum | 40% | 20-bar return — determines trend direction |
    | Volume Factor  | 30% | Volume expansion check — volume-price alignment strengthens the signal |
    | Volatility Factor | 30% | Current market volatility — reduces signal strength when vol is high |

    **Trading Rules:**
    - Composite score > **0.4** → Buy (deploy 95% of available cash)
    - Composite score < **-0.4** → Sell (liquidate full position)
    - Otherwise → Hold

    **Signal Execution (no look-ahead bias):**
    - Factor score is computed from bar i's close data
    - Actual fill occurs at bar i+1's **open price** (including slippage)
    - Guarantees the strategy never uses future information

    **Risk Controls:**
    - Commission: 0.1% (Binance spot standard)
    - Slippage: trade value × 0.02% (conservative market impact estimate)
    - Max drawdown stop: 15% (trading halts if breached)
    """)


# ================================================================
# TCA Cost Analysis page
# ================================================================

elif mode == "TCA Cost Analysis":
    st.title("💸 TCA — Transaction Cost Analysis")

    st.markdown("""
    **TCA (Transaction Cost Analysis)** quantifies the explicit and implicit costs
    generated by each trade, which directly affects the strategy's actual profitability.

    > **Note:** This system implements an educational-grade TCA. Slippage is estimated
    > as an empirical proportion of trade value (conservative for BTC spot, a highly liquid market)
    > rather than from real order-book data or a market impact model.
    """)

    metrics, _, _, bt_trades = load_backtest_cache()

    if metrics is not None:
        total_trades      = metrics.get("total_trades", 0)
        final_val         = metrics.get("final_value", 50000)
        net_profit        = final_val - 50000
        total_commission  = metrics.get("total_commission", 0)
        total_slippage    = metrics.get("total_slippage", 0)
        total_cost        = total_commission + total_slippage
        cost_vs_profit    = (total_cost / abs(net_profit) * 100) if net_profit != 0 else 0

        col1, col2, col3 = st.columns(3)
        with col1:
            st.metric("💰 Total Commission",
                      f"{total_commission:.2f} USDT",
                      f"{total_trades} trades × 0.1%",
                      delta_color="inverse")
        with col2:
            st.metric("📉 Estimated Slippage",
                      f"{total_slippage:.2f} USDT",
                      "Trade value × 0.02% estimate",
                      delta_color="inverse")
        with col3:
            st.metric("📊 Cost / P&L Ratio",
                      f"{cost_vs_profit:.1f}%",
                      "Excellent < 10%" if cost_vs_profit < 10 else "High — needs optimisation",
                      delta_color="normal" if cost_vs_profit < 10 else "inverse")
    else:
        c1, c2, c3 = st.columns(3)
        c1.metric("💰 Total Commission", "-- USDT")
        c2.metric("📉 Estimated Slippage",   "-- USDT")
        c3.metric("📊 Cost / P&L Ratio","-- %")

    st.divider()

    # ---- Order cost breakdown ----
    st.subheader("📋 Order Cost Breakdown")
    db_orders = get_recent_orders(limit=50)

    if db_orders:
        # Prefer Paper Trading database records
        df_o = pd.DataFrame(db_orders)
        df_o["Trade Value (USDT)"]     = df_o["price"] * df_o["qty"]
        df_o["Commission (USDT)"]      = df_o["Trade Value (USDT)"] * 0.001
        df_o["Est. Slippage (USDT)"]   = df_o["Trade Value (USDT)"] * 0.0002
        df_o["Total Cost (USDT)"]      = df_o["Commission (USDT)"] + df_o["Est. Slippage (USDT)"]
        show = df_o[["order_id", "side", "price", "qty",
                     "Trade Value (USDT)", "Commission (USDT)",
                     "Est. Slippage (USDT)", "Total Cost (USDT)"]].copy()
        show = show.rename(columns={"order_id": "Order ID", "side": "Direction",
                                    "price": "Price", "qty": "Qty"})
        for col in ["Trade Value (USDT)", "Commission (USDT)", "Est. Slippage (USDT)", "Total Cost (USDT)"]:
            show[col] = show[col].apply(lambda x: f"{x:.2f}")
        st.dataframe(show, use_container_width=True)
        n_orders = len(db_orders)

    elif bt_trades:
        # Fallback: compute cost breakdown from backtest fills
        st.caption("📊 Showing backtest trade costs (will be replaced by live data once Paper Trading starts)")
        rows = []
        for t in bt_trades:
            price     = t.get("price", 0)
            qty       = t.get("qty", 0)
            trade_val = price * qty
            fee       = t.get("fee", trade_val * 0.001)
            slippage  = t.get("slippage", trade_val * 0.0002)
            rows.append({
                "Direction":            t.get("action", "—"),
                "Price (USDT)":         f"{price:,.2f}",
                "Qty (BTC)":            f"{qty:.6f}",
                "Trade Value (USDT)":   f"{trade_val:,.2f}",
                "Commission (USDT)":    f"{fee:.4f}",
                "Est. Slippage (USDT)": f"{slippage:.4f}",
                "Total Cost (USDT)":    f"{fee + slippage:.4f}",
                "P&L (USDT)":           f"{t.get('pnl', 0):+.2f}" if t.get("action") == "sell" else "—",
            })
        df_bt = pd.DataFrame(rows)

        def color_side(val):
            if val == "buy":
                return "background-color: #003300; color: #00ff00"
            elif val == "sell":
                return "background-color: #330000; color: #ff4444"
            return ""

        st.dataframe(
            df_bt.style.map(color_side, subset=["Direction"]),
            use_container_width=True,
        )
        n_orders = len(bt_trades)

    else:
        st.info("No trade records available.")
        n_orders = 0

    st.divider()

    st.subheader("💡 TCA Concepts & Limitations")
    st.markdown(f"""
    | Cost Type | Explanation | Impact on This Strategy | Calculation |
    |-----------|-------------|------------------------|-------------|
    | **Commission** | Fee paid to the exchange per trade | Binance spot 0.1% — relatively low | Trade value × 0.10% |
    | **Slippage** | Difference between signal price and actual fill price | BTC is highly liquid; estimated at 0.02% | Trade value × 0.02% |
    | **Market Impact** | Cost of large orders moving the price | BTC daily volume is massive — negligible | Not modelled |
    | **Timing Cost** | Price drift between signal and fill | Next-bar open price execution | next-bar execution |

    **TCA System Limitations:**
    - Slippage is estimated using an empirical ratio, not real order-book data — this is an **educational-grade TCA**
    - No complete market impact model (e.g. Almgren-Chriss model) has been implemented
    - Slippage estimates are only valid for high-liquidity instruments such as BTC/USDT spot

    > **Conclusion:** This strategy trades infrequently (only **{n_orders}** trades over 7 days).
    > The combined commission and slippage cost is manageable and has a small impact on overall profitability.
    """)
